# Generated by Django 5.2.8 on 2026-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menber_JESFOD', '0002_member_profile_photo_member_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='activities',
            field=models.TextField(blank=True, help_text='Activités et responsabilités du membre'),
        ),
    ]
