# Generated by Django 6.0.4 on 2026-07-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menber_JESFOD', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('president', 'Président(e)'), ('vice_president', 'Vice-Président(e)'), ('secretaire_general', 'Secrétaire Général(e)'), ('secretaire_adjoint', 'Secrétaire Adjoint(e)'), ('tresorier', 'Trésorier(e)'), ('tresorier_adjoint', 'Trésorier(e) Adjoint(e)'), ('charge_com', 'Chargé(e) de Communication'), ('conseiller', 'Conseiller(e)'), ('membre', 'Membre du Bureau')], default='membre', help_text='Poste occupé au sein du bureau (si applicable)', max_length=50),
        ),
    ]
