# Generated by Django 6.0.4 on 2026-07-19 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menber_JESFOD', '0006_member_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('inscription', 'Inscription'), ('fdr', 'Fonds de Roulement'), ('amande', 'Amende'), ('tontine', 'Tontine')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, default=500, help_text='Montant en FCFA', max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('period', models.CharField(blank=True, help_text='Période ex: 07/2026 (pour FDR/Tontine)', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observations / motif amende')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='menber_JESFOD.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_finances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrée Financière',
                'verbose_name_plural': 'Entrées Financières',
                'ordering': ['-created_date'],
            },
        ),
    ]
