# Generated by Django 6.0.4 on 2026-07-22 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menber_JESFOD', '0007_alter_member_phone_financeentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Séance ordinaire', max_length=200)),
                ('date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(blank=True, help_text="Motif de l'absence", max_length=200, null=True)),
                ('justifiee', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='menber_JESFOD.member')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='menber_JESFOD.seance')),
            ],
            options={
                'ordering': ['-seance__date'],
                'unique_together': {('member', 'seance')},
            },
        ),
    ]
