# Generated by Django 6.0.4 on 2026-08-15 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menber_JESFOD', '0008_seance_absence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('president', 'Président(e)'), ('vice_president', 'Vice-Président(e)'), ('secretaire_general', 'Secrétaire Général(e)'), ('secretaire_adjoint', 'Secrétaire Adjoint(e)'), ('tresorier', 'Trésorier(e)'), ('tresorier_adjoint', 'Trésorier(e) Adjoint(e)'), ('charge_com', 'Chargé(e) de Communication'), ('conseiller', 'Conseiller(e)'), ('membre', 'Membre du Bureau'), ('membre_reunion', 'Membre de Réunion')], default='membre', help_text='Poste occupé au sein du bureau (si applicable)', max_length=50),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='menber_JESFOD.member')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='menber_JESFOD.seance')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('member', 'seance')},
            },
        ),
    ]
