# Generated by Django 5.2.17 on 2026-09-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menber_JESFOD', '0009_event_video_news_video_alter_member_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('president', 'Président(e)'), ('vice_president', 'Vice-Président(e)'), ('secretaire_general', 'Secrétaire Général(e)'), ('secretaire_adjoint', 'Vice-Secrétaire'), ('censeur', 'Censeur'), ('charge_culturel', 'Chargé(e) des Affaires Culturelles'), ('charge_com', 'Chargé(e) de Communication'), ('charge_animation', 'Chargé(e) Animation'), ('tresorier', 'Trésorier(e)'), ('tresorier_adjoint', 'Trésorier(e) Adjoint(e)'), ('commissaire_comptes', 'Commissaire aux Comptes'), ('charge_sport', 'Chargé(e) des Sports'), ('sante', 'Chargé(e) de la Santé'), ('conseiller', 'Conseiller(e)'), ('membre', 'Membre du Bureau'), ('membre_reunion', 'Membre de Réunion')], default='membre', help_text='Poste occupé au sein du bureau (si applicable)', max_length=50),
        ),
    ]
