# Generated by Django 6.0.4 on 2026-08-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_JESFOD', '0003_alter_news_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
